import { chromium } from 'C:/Users/NITZAN/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:3333');
await page.waitForTimeout(3000);
await page.screenshot({ path: 'C:/Users/NITZAN/AppData/Local/Temp/swipe_before.png' });
await page.mouse.click(195, 450);
await page.waitForTimeout(1500);
await page.screenshot({ path: 'C:/Users/NITZAN/AppData/Local/Temp/swipe_after.png' });
await browser.close();
console.log('done');
