// JoBoss feature:
// - F-22: Preference Mismatch Warning Modal

import { motion, AnimatePresence } from 'framer-motion';
import useTranslation from '../i18n/useTranslation';

function MismatchWarningModal({ visible, reason, onCancel, onContinue }) {
  const { t } = useTranslation();

  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          style={styles.overlay}
          onClick={onCancel}
        >
          <motion.div
            initial={{ scale: 0.85, opacity: 0, y: 30 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.85, opacity: 0, y: 30 }}
            transition={{ type: 'spring', damping: 22, stiffness: 300 }}
            style={styles.modal}
            onClick={e => e.stopPropagation()}
          >
            <div style={styles.iconWrap}>
              <span style={{ fontSize: '32px' }}>⚠️</span>
            </div>

            <h2 style={styles.title}>{t('mismatch.title')}</h2>

            {/* `reason` is generated by the AI in Hebrew, so it is passed through
                as-is rather than translated — only the chrome around it. */}
            <p style={styles.body}>{reason || t('mismatch.defaultReason')}</p>

            <p style={styles.sub}>{t('mismatch.note')}</p>

            <div style={styles.actions}>
              <button style={styles.cancelBtn} onClick={onCancel}>{t('mismatch.cancel')}</button>
              <button style={styles.continueBtn} onClick={onContinue}>{t('mismatch.continue')}</button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

const styles = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(4px)',
    zIndex: 400, display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '20px',
  },
  modal: {
    background: 'white', borderRadius: '24px', padding: '32px 24px',
    maxWidth: '380px', width: '100%', display: 'flex', flexDirection: 'column',
    alignItems: 'center', gap: '14px', boxShadow: '0 24px 64px rgba(0,0,0,0.22)',
    direction: 'inherit', textAlign: 'center',
  },
  iconWrap: {
    width: '68px', height: '68px', borderRadius: '50%',
    background: 'linear-gradient(135deg, #FFF3CD, #FFC107)',
    display: 'flex', justifyContent: 'center', alignItems: 'center',
  },
  title: { fontSize: '20px', fontWeight: 800, margin: 0, color: '#1E2A4A' },
  body: { fontSize: '14px', color: '#374151', margin: 0, lineHeight: 1.65 },
  sub: { fontSize: '12px', color: '#9CA3AF', margin: 0 },
  actions: { display: 'flex', gap: '10px', width: '100%', marginTop: '4px' },
  cancelBtn: {
    flex: 1, padding: '12px', borderRadius: '14px',
    border: '1.5px solid #E5E7EB', background: 'white',
    color: '#374151', fontSize: '14px', fontWeight: 700, cursor: 'pointer',
  },
  continueBtn: {
    flex: 1, padding: '12px', borderRadius: '14px',
    border: 'none', background: 'linear-gradient(135deg, #6C4FD4, #1E2A4A)',
    color: 'white', fontSize: '14px', fontWeight: 700, cursor: 'pointer',
  },
};

export default MismatchWarningModal;
